- name: Install base packages
  apt:
    name:
      - gnupg2
      - mosh
      - netcat
      - tmate
    state: present
    update_cache: yes

- name: Install shells
  apt:
    name:
      - fish
      - zsh
    state: present
    update_cache: yes
