- name: Install base packages
  apt:
    name:
      - apt-transport-https # for ppa
      - ca-certificates # for ppa
      - certbot # for pterodactyl
      - curl
      - fish  # for johnny
      - git
      - git-lfs # helps a lot with lowering tick stutter
      - gnupg2
      - iptables-persistent # might need a flag
      - ipset # for ipt
      - jq # for discord webhooks + ci
      - linux-image-rt-amd64  # helps a lot with lowering tick stutter
      - lsb-release # for ppa
      - mosh  # for ssh
      - net-tools # for iptables srcds hardening script
      - netcat
      - python3-docker # for ansible
      - software-properties-common
      - tmate
      - tmux  
      - unzip
      - zip
      - zsh # for steph
    state: present
    update_cache: yes
