- name: Install base packages
  apt:
    name:
      - git
      - gnupg2
      - mosh
      - netcat
      - tmux
      - tmate
      - fish
      - zsh
      - net-tools
    state: present
    update_cache: yes
