- hosts: gameservers
  become: true
  become_user: root
  gather_facts: true
  serial: "{{ serial | default(0) }}"
  handlers:
    - include: handlers/main.yml
  roles:
    - role: 'shared/users'
      tags: users

    - role: 'shared/packages'
      tags: packages

    - role: 'shared/docker'
      tags: docker

    - role: 'shared/netdata-ntop-demos'
      tags: nginx

    - role: 'shared/cronjob'
      tags: cronjob

    - role: 'gameservers/wings'
      tags: wings

    - role: 'gameservers/runner'
      tags: runner

    - role: 'shared/firewall'
      tags: firewall

    - role: 'shared/unattended-upgrades'
      tags: unattended-upgrades
