- import_tasks: 010-wings.yml
  tags: wings-service

# WIP
# - import_tasks: 020-config.yml
#   tags: wings-config

- name: Start and Enable Wings
  service:
    name: wings
    state: started
    enabled: yes
  tags: molecule-notest
