gameservers:
  children:
    na:
      hosts:
        vin.servers.creators.tf:2222:
        la.servers.creators.tf:2222:
    eu:
      hosts:
         139.59.135.178:2222:
         135.125.188.102:2222:
             ansible_user: debian
#        eu.servers.creators.tf:2222:
#        178.33.236.38:2222:
    oce:
      hosts:
        aus.servers.creators.tf:2222:
        sgp.servers.creators.tf:2222:
