- name: Configure UFW
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/ufw/after.rules
  notify:
    - restart ufw

# Ensure ufw is restarted before proceeding
- meta: flush_handlers # noqa unnamed-task

- name: Allow rules
  ufw:
    port: "{{ item }}"
    direction: incoming
    policy: allow
  with_items:
    - http
    - https
    - mosh
    - ssh
    - '2222'
    - '8080'

- name: Deny rules
  ufw:
    direction: incoming
    policy: deny

- name: Allow routed ports
  ufw:
    direction: routed
    port: "{{ item }}"
    policy: allow
  with_items:
    - http
    - https
    - mysql

- name: Allow routed udp
  ufw:
    direction: routed
    port: 27000:27100
    proto: udp
    policy: allow

- name: Allow from ip
  ufw:
    direction: routed
    from_ip: 178.33.236.38
    policy: allow

- name: Enable rules
  ufw:
    state: enabled
