- name: Configure UFW
  debug:
    msg: todo

# sudo systemctl restart ufw
# sudo ufw allow https
# sudo ufw allow http
# sudo ufw allow mosh
# sudo ufw allow 2222
# sudo ufw allow 8080
# sudo ufw default deny incoming
# sudo ufw default allow outgoing
# sudo ufw enable
# sudo ufw route allow 27000:27100/udp
# sudo ufw route allow from 178.33.236.38
# sudo ufw route allow https
# sudo ufw route allow http
# sudo ufw route allow mysql
