- name: Reset UFW rules
  community.general.ufw:
    state: reset

- name: Setup UFW-DOCKER
  synchronize:
    dest_port:  2222
    # so ufw doesn't whine abt perms
    archive: no
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/ufw/after.rules
  become: true

# RELOAD IT
# This is *needed* because otherwise rules get cleared and not readded to iptables' INPUT
- name: UFW RELOAD
  community.general.ufw:
    state: reloaded

- name: temp allow incoming
  community.general.ufw:
    default: allow
    direction: incoming

- name: Allow routed udp
  community.general.ufw:
    rule: allow
    route: yes
    port: 27000:29999
    proto: udp
    comment: 'gameserver ports'

- name: Enable rules and restart UFW
  community.general.ufw:
    state: enabled
  notify:
    - restart ufw

- name: UFW allow ssh
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
    comment: 'ssh'

- name: UFW allow ssh 2222
  community.general.ufw:
    rule: allow
    port: '2222'
    proto: tcp
    comment: 'ssh alt'



- name: UFW allow http
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    comment: 'http'


- name: UFW allow https
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
    comment: 'https'

- name: UFW allow mosh
  community.general.ufw:
    rule: allow
    port: 60000:61000
    proto: udp
    comment: 'mosh'

- name: UFW allow 8443
  community.general.ufw:
    rule: allow
    port: '8443'
    proto: tcp
    comment: 'pterodactyl https'

- name: UFW allow docker to communicate with local gameservers
  community.general.ufw:
    rule: allow
    from_ip: 172.16.0.0/12
    comment: 'allow docker to communicate with itself'

# ROUTED
- name: Allow routed http
  community.general.ufw:
    rule: allow
    route: yes
    port: '80'
    proto: tcp
    comment: 'connplex/motd http'

- name: Allow routed https
  community.general.ufw:
    rule: allow
    route: yes
    port: '443'
    proto: tcp
    comment: 'connplex/motd https'

# DEFAULTS

- name: Default allow outgoing
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Default deny incoming
  community.general.ufw:
    default: deny
    direction: incoming

# RESTART IT

- name: Enable rules and restart UFW
  community.general.ufw:
    state: enabled
  notify:
    - restart ufw
