- name: Ensure auth log exists
  file:
    path: /var/log/auth.log
    access_time: preserve
    modification_time: preserve
    state: touch

- name: Configure fail2ban
  synchronize:
    dest_port:  2222
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/fail2ban/action.d/ufw-log.conf
    - etc/fail2ban/jail.d/ssh-ufw-log.conf
  notify:
    - restart fail2ban
  become: true


