- name: Ensure auth log exists
  file:
    path: /var/log/auth.log
    # owner: syslog
    # group: adm
    # mode: 0640
    access_time: preserve
    modification_time: preserve
    state: touch

- name: Configure fail2ban
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/fail2ban/action.d/ufw-log.conf
    - etc/fail2ban/jail.d/ssh-ufw-log.conf
  notify:
    - restart fail2ban

