- name: Create scripts folder
  file:
    path: /opt/scripts/
    state: directory

- name: Get scripts
  get_url:
    url: "{{ item }}"
    dest: /opt/scripts/
    mode: '0700'
    force: yes
  with_items:
    - https://raw.githubusercontent.com/CreatorsTF/srcds-hardening-iptables-docker/main/ipt.sh
    - https://raw.githubusercontent.com/CreatorsTF/stvmover/main/stvmover.sh
