- name: Download GitLab Runner installation script
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: 0400
    force: yes

- name: Execute GitLab Runner installation script
  command: bash /tmp/script.deb.sh
  tags: install-gitlab-runner

- name: Apt Install GitLab Runner
  apt:
    name:
      - gitlab-runner
    state: present
    update_cache: yes

- name: Uninstall any existing GitLab Runner Service
  become_user: root
  ansible.builtin.shell: |
  gitlab-runner uninstall

- name: Install GitLab Runner as a systemd service
  become_user: root
  ansible.builtin.shell: |
  gitlab-runner install -u=gitlab-runner

