- name: remove apt garbage
  hosts: gameservers
  become: true
  tasks:
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
