- name: Add php repository key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add php repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    update_cache: yes

- name: Install php 8
  apt:
    name:
      - php8.0-fpm
      - php8.0-common
    state: present
