- name: Download Netdata
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /tmp/kickstart.sh
    mode: 0500
    force: yes

- name: Install Netdata
  command: /tmp/kickstart.sh --dont-wait --stable-channel --disable-telemetry

